
CREATE DATABASE url_db;
USE url_db;
CREATE TABLE url(id INT NOT NULL IDENTITY(1,1), url TEXT NOT NULL, code VARCHAR(255) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id));
